version: "3.7"
services:
  jottad:
    image: "kenavn/jottadock:latest"
    volumes:
      - type: bind
        source: /share/Kenneth
        target: /share/Kenneth
        read_only: true
      
      - type: volume
        source: jottad_config
        target: /var/lib/jottad
volumes:
  jottad_config: