version: "3.7"
services:
  jottad:
    image: "kenavn/jottadock:latest"
    volumes:
      - type: bind
        source: /share/Kenneth
        target: /share/Kenneth
        read_only: true

      - type: bind
        source: /share/Cathrine
        target: /share/Cathrine
        read_only: true

      - type: bind
        source: /share/Multimedia
        target: /share/Multimedia
        read_only: true

      - type: bind
        source: /share/Public
        target: /share/Public
        read_only: true

      - type: bind
        source: /share/Retro
        target: /share/Retro
        read_only: true

      - type: volume
        source: jottad_config
        target: /var/lib/jottad

      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        
volumes:
  jottad_config: